### ISSUE TITLE
CLI does not play nicely with Sass parent selector

### ISSUE THREAD

**Issue by sporeball** [sporeball/linn#2]
when the CLI encounters a rule that uses Sass' [parent selector](https://sass-lang.com/documentation/style-rules/parent-selector), e.g.
```css
main {
  ul, ol {
    list-style:none;
    color:blue;
    &:before {
      color:lightblue;
      margin-left:-2rem
    }
  }
}
```
, the style regex doesn't work properly anymore, and nothing happens.

i have no idea how long this will take to fix, but it would be really nice.
